id: I245B56F4
legacy_id: P001694
ocr_import_info:
  bdrc_scan_id: W29222
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T06:59:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T10:13:37.291612+00:00'
last_modified: 2022-09-02 18:13:57.264686
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29222
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29222
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྟན་བཅོས་ཙིན་དྷ་མ་ཎི་རིན་པོ་ཆེ་འབར་བའི་ཕྲེང་བ།
  author: ཉེ་གནས་གྲགས་པ་རིན་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.9700157415860517
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I5537:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5537
      total_pages: 286
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5537.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9700157415860517
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
